### ISSUE TITLE
iif: architect and develop [6]

### ISSUE THREAD

**Issue by joshjung** [jung-digital/ringa#1]
Target code:

```
controller.addListener('testEvent', [
  iif(someValue => someValue === true, TruthyCommand, FalsyCommand)
]);

Ring.dispatch('testEvent', {someValue: true});
```

For information on what an 'iif' is, take a look here: https://en.wikipedia.org/wiki/IIf

**Comment by corragon** [comment]
58a662050b0aee3a21f663bd197e8aad4334085f
14f3d5ca9836536985827b2ba39b533d4182b6fa
