### ISSUE TITLE
Executors: add 'interval' executor

### ISSUE THREAD

**Issue by joshjung** [jung-digital/ringa#53]
Target code:

```
controller.addListener('myEvent', [
  interval(conditionCallback, executor, milliseconds)
]);
```

This will check `conditionCallback` and as long as it returns true, it would run `executor` every `milliseconds`. Once `conditionCallback` returns false, then it continues to the next `executor`.

This should allow for the ability to create primitive animations!

**Comment by corragon** [comment]
Closed by PR #58
