### ISSUE TITLE
Executors: create `while` executor

### ISSUE THREAD

**Issue by joshjung** [jung-digital/ringa#82]
We need a while executor, that checks a condition function every loop and repeats a loopExecutor each time.

Target Code:

```
controller.addListener('whileEvent', [
  while(condition, loopExecutor)
]);
```

**Comment by corragon** [comment]
while is a reserved word, so we'll need another name for this syntax.  Maybe we could use `loop` instead of `while`?  I don't care much for `wwhile`.  Even stranger would be using `ifdo`

**Comment by joshjung** [comment]
Let's use loop for now. This is as you pointed out basically an interval executor with a 0ms timeout.
